name: driftapp Deploy
on:
  push:
    branches:
      - develop    # change to main if needed
      - feat-drift-app
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_DRIFT_TOKEN }}
        working-directory: ee/drift/